version: '3.1'

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pguser
      POSTGRES_DB: pgdb
    ports:
      - 5432:5432