apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: helm-repositories
  namespace: openfaas-fn
spec:
  handler: node index.js
  image: phumberdroz/helm-notifier-repositories:{{ .Values.image.tag }}
  name: helm-repositories
  replicas: 1
  secrets:
  - database-uri